import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Sidebar from '@/components/Sidebar'
import TopCard from '@/components/TopCard'
import BarChart from '@/components/BarChart'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-900 min-h-screen'>
        <Sidebar />
        <Header />
        <TopCard />

        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <BarChart />
        </div>
      </main>
    </>
  )
}
